export interface Ticket 
{
    // Generated by https://quicktype.io
    id:            number;
    name:          string;
    email:         string;
    ticketIssue:   string;
    ticketDetails: string;
    resolvedBy:    string;
    favorites:     any[];
    canDisplay:    boolean;
}

